# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle on Dev_Branches

on:
  push:
    branches-ignore:
      - master
      
  pull_request:
    branches-ignore:
      - master
      
jobs:
    Java_CI:
      strategy:
        matrix:
         java: ['8','11']
         
      runs-on: ubuntu-latest

      steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java }}
          distribution: 'adopt'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew assemble
      - name: Run Tests
        run: ./gradlew check --info
