name: Lint Java Code
on:
  [push,pull_request]
jobs:
  Lint_Java:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Lint_Java
        uses: github/super-linter@v3
        env:
          VALIDATE_ALL_CODEBASE: false # only lint new files
          VALIDATE_JAVA: true  # only lint Java files
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Enables better overview of runs
